config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'points/:word_id/correct_answer' => 'points#correct_answer', as: :correct_answer
  get 'points/:word_id/wrong_answer' => 'points#wrong_answer', as: :wrong_answer

  get 'games/random_words' => 'games#random_words', as: :random_words

  get 'games/:list' => 'games#list', as: :list
  get 'games/:list/hard_words/' => 'games#hard_words', as: :hard_words
  get 'games/:list/practice/' => 'games#practice', as: :practice

  resources :words

end

app/models/point.rb
class Point
  include Mongoid::Document
  include Mongoid::Timestamps

  field :value,   type: Integer, default: -> { 0 }

  validates :word_id, :value, presence: true

  belongs_to :word

  def self.test_words(words)
    words
  end

  def self.total_points
    points = self.pluck(:value)
    sum = 0
    points.each do |v|
      sum += v
    end
    sum
  end

  def self.todays_points
    points = self.where(:created_at.gt => Time.zone.now.beginning_of_day).pluck(:value)
    sum = 0
    points.each do |v|
      sum += v
    end
    sum
  end
end

app/models/word.rb
class Word
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name

  validates :name, presence: true
  validates :name, uniqueness: true

  index({ name: 1 }, { unique: true, name: "name_index" })

  before_save :downcase_name

  has_many :points, dependent: :restrict

  def downcase_name
    self.name = self.name.downcase unless self.name == "I"
  end

  def right
    self.points.where(value: 1).count
  end

  def wrong
    self.points.where(value: 0).count
  end

  # Returns a lambda used to determine what number is at t in the range of a and b
  #
  #   interpolate_number(0, 500).call(0.5) # 250
  #   interpolate_number(0, 500).call(1) # 500
  #
  def interpolate(a, b)
    a = a.to_f
    b = b.to_f
    b -= a

    lambda { |t| a + b * t }
  end

  # Returns a lambda used to determine where t lies between a and b with an ouput
  # range of 0 and 1
  #
  #   uninterpolate_number(0, 500).call(0)   # 0
  #   uninterpolate_number(0, 500).call(250) # 0.5
  #   uninterpolate_number(0, 500).call(500) # 1.0
  #
  def uninterpolate
    a = 0.0
    b = (wrong + right).to_f
    b = b - a > 0 ? 1 / (b - a) : 0

    lambda { |x| (x - a) * b }
  end

  # Returns a closure with the specified input domain and output range
  #
  #   score = scale([0, 500], [0, 1.0])
  #
  #   score.call(0) = 0
  #   score.call(250) = 0.5
  #   score.call(500) = 1.0
  #
  #
  # domain - Array. Input domain
  # range  - Array. Output range
  #
  # Returns lambda
  def scale(range)
    u = uninterpolate
    i = interpolate(range[0], range[1])

    lambda do |x|
      x = ([0.0, x, (wrong + right).to_f].sort[1]).to_f
      i.call(u.call(x))
    end
  end

  def difficulty(scale=[1.0, 10.0])
    scale(scale).call(wrong)
  end

  def self.difficulty_set(list, score=0.0, direction="higher")
    words = []
    where(:name.in => list).each do |w|
      if direction == "higher"
        words << w if w.difficulty >= score.to_f
      else
        words << w if w.difficulty <= score.to_f
      end
    end
    words
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_points

  def random_words
    @word = Word.difficulty_set(SIGHT_WORDS, 1, "higher").sample
  end

  def list
    @list_name = params[:list].to_s.upcase
    @list = Kernel.const_get @list_name
    @words = Word.difficulty_set(@list, 6, "lower")
    @word = @words.sample
  end

  def hard_words
    @list_name = params[:list].to_s.upcase
    @list = Kernel.const_get @list_name
    @words = Word.difficulty_set(@list, 4)
    @word = @words.sample
  end

  def practice
    @list_name = params[:list].to_s.upcase
    @list = Kernel.const_get @list_name
    @words = Word.difficulty_set(@list, 1, "higher")
    @word = @words.sample
  end

  private
    def set_points
      @total_points = Point.total_points
      @todays_points = Point.todays_points
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController

  def correct_answer
    @word = Word.find(params[:word_id])
    if @word
      @point = Point.new(value: 1, word_id: @word.id)
      if @point.save
        flash[:notice] = "Awesome job. You are correct!!"
        redirect_to :back
      else
        flash.now[:error] = "There was an error adding points. Please try again."
        redirect_to root_path
      end
    else
      flash.now[:error] = "You need to provide a word to get a correct answer."
      redirect_to root_path
    end
  end

  def wrong_answer
    @word = Word.find(params[:word_id])
    if @word
      @point = Point.new(value: 0, word: @word.id)
      if @point.save
        flash[:error] = "Sorry Layla. But the answer is wrong. Please try another word."
        redirect_to :back
      else
        flash.now[:error] = "There was an error adding points. Please try again."
        redirect_to root_path
      end
    else
      flash.now[:error] = "You need to provide a word to get a correct answer."
      redirect_to root_path
    end
  end

  private
    def set_point
      @point = Point.find(params[:id])
    end
    def point_params
      params.require(:point).permit(:value, :word_id)
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update]

  respond_to :html

  def index
    @words = Word.all.sort { |x, y| x.name <=> y.name }
  end

  def show
    respond_with(@word)
  end

  def new
    @word = Word.new
    respond_with(@word)
  end

  def create
    @word = Word.new(word_params)
    if @word.save
      flash[:notice] = "Your word has been created."
      respond_with(@word)
    else
      flash.now[:error] = "There was an error creating your word. Please try again."
      render :new
    end
  end

  def edit
    respond_with(@word)
  end

  def update
    if @word.update_attributes(word_params)
      flash[:notice] = "Your word has been updated!"
      respond_with(@word)
    else
      flash.now[:error] = "There was an error updating your word. Please try again."
      render :edit
    end
  end

  private
    def set_word
      @word = Word.find(params[:id])
    end

    def word_params
      params.require(:word).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_layout.html.erb
<div class="row full-width">
  <div class="small-12 columns">
    <div class="text-center">
      <h1>Hi Layla! <%= list_name.downcase.split("_").map { |x| x.capitalize }.join(" ") %></h1>
      <h3 class="subheader"><%= list.join(", ") %></h3>
      <p>
        <%= link_to "Normal Words", list_path(params[:list]),
            data: { no_turbolink: true } %> |
        <%= link_to "Hard Words", hard_words_path(params[:list]),
            data: { no_turbolink: true } %> |
        <%= link_to "Practice", practice_path(params[:list]) %>
      </p>
    </div>
  </div>
  <hr>
  <% if word %>
      <div class="row">
        <%= render 'points', todays_points: todays_points, total_points: total_points %>
        <%= render 'word', word: word %>
      </div>
      <div class="row">
        <div class="small-12 columns text-center">
          <h4><%= words.count %> Remaining Words</h4>
          <p class="panel">
            <% names = [] %>
            <% words.each do |w| %>
              <% names << w.name %>
            <% end %>
            <%= names.join(", ") %>
          </p>
        </div>
      </div>
  <% else %>
    <p class="panel text-center">
      There are currently no words left to practice for
      <%= list_name.downcase.split("_").join(" ") %>.
    </p>
  <% end %>
  <% if todays_points >= 10 %>
    <%= render 'success', total_points: total_points %>
  <% end %>
</div>

app/views/games/_points.html.erb
<div class="small-12 medium-6 columns">
  <h1 class="text-center score">
    Today<br>
    <span class="point-number"><%= todays_points %></span><br>
    Left<br>
    <span class="point-number"><%= todays_points <= 10 ? 10 - todays_points : 0 %></span>
  </h1>
  <h1 class="text-center score">
    Total<br>
    <span class="point-number"><%= total_points %></span>
  </h1>
</div>

app/views/games/_success.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1 class="text-center">Great job Layla! You earned 10 points today!</h1>
    <h1 class="text-center score">
      Total Points<br>
      <%= total_points %>
    </h1>
    <hr>
    <h1 class=text-center>Points left to earn your mermaid project.</h1>
    <h1 class="text-center score">
      Total Points<br>
      <%= total_points < 1100 ? 1100 - total_points : 0 %>
    </h1>
    <div class="text-center"><%= image_tag "mermaid.jpg" %></div>
  </div>
</div>

app/views/games/_word.html.erb
<div class="small-12 medium-6 columns">
  <h1 class="text-center">
    What sight word is this?<br><br>
    <span class="random-word"><%= word.name %></span>
  </h1>
  <hr>
  <div class="text-center">
    <p>
      <%= link_to "Correct", correct_answer_path(word.id) , class: 'button success' %>
      <%= link_to "Incorrect", wrong_answer_path(word.id), class: 'button alert' %>
    </p>
  </div>
  <div class="text-center">
    <p class="subheader">Difficulty: <%= word.difficulty.round(2) %></p>
  </div>
</div>

app/views/games/hard_words.html.erb
<%= render 'layout', word: @word, list_name: @list_name,
    todays_points: @todays_points, total_points: @total_points,
    list: @list, words: @words %>

app/views/games/list.html.erb
<%= render 'layout', word: @word, list_name: @list_name,
    todays_points: @todays_points, total_points: @total_points,
    list: @list, words: @words %>

app/views/games/practice.html.erb
<%= render 'layout', word: @word, list_name: @list_name,
    todays_points: @todays_points, total_points: @total_points,
    list: @list, words: @words %>

app/views/games/random_word.html.erb
<div class="row full-width">
  <div class="small-12 columns">
    <h1 class="text-center">Hi Layla!</h1>
  </div>
  <hr>
  <% if @todays_points == 10 %>
    <%= render 'success', total_points: @total_points %>
  <% else %>
    <%= render 'points', todays_points: @todays_points, total_points: @total_points %>
    <%= render 'word', word: @word %>
  <% end %>
</div>

app/views/games/random_words.html.erb
<div class="row full-width">
  <div class="small-12 columns">
    <h1 class="text-center">Hi Layla! Random Words</h1>
  </div>
  <hr>
  <% if @todays_points == 10 %>
    <%= render 'success', total_points: @total_points %>
  <% else %>
    <%= render 'points', todays_points: @todays_points, total_points: @total_points %>
    <%= render 'word', word: @word %>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<!-- Navbar -->
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Layla's Site Words!", root_path, data: { no_turbolink: true } %></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="has-dropdown">
        <%= link_to "Games", root_path, data: { no_turbolink: true } %>
        <ul class="dropdown">
          <li><%= link_to "List One", list_path(:list_one), data: { no_turbolink: true } %></li>
          <li><%= link_to "List Two", list_path(:list_two), data: { no_turbolink: true } %></li>
          <li><%= link_to "List Three", list_path(:list_three), data: { no_turbolink: true } %></li>
          <li><%= link_to "List Four", list_path(:list_four), data: { no_turbolink: true } %></li>
          <li><%= link_to "Random Words", random_words_path, data: { no_turbolink: true } %></li>
        </ul>
      </li>
      <li class="has-dropdown">
        <%= link_to "Words", words_path, data: { no_turbolink: true } %>
        <ul class="dropdown">
          <li><%= link_to "New Word", new_word_path, data: { no_turbolink: true } %></li>
        </ul>
      </li>
    </ul>
  </section>
</nav>

app/views/layouts/_notices.html.erb
<% if flash[:notice] %>
  <div data-alert class="alert-box success text-center">
    <%= flash[:notice] %>
    <%= link_to "X", '#', class: 'close' %>
  </div>
<% elsif flash[:error] %>
  <div data-alert class="alert-box alert text-center">
    <%= flash[:error] %>
    <%= link_to "X", '#', class: 'close' %>
  </div>
<% elsif flash[:alert] %>
  <section class="alert">
    <div data-alert class="alert-box warning text-center">
      <h3><%= flash[:alert] %></h3>
      <%= link_to "X", '#', class: 'close' %>
    </div>
  </section>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/notices' %>
    <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="row">
  <div class="small-12 columns">
    <div class="text-center">
      <h1>Sight Words Practice</h1>
      <h2 class="subheader">Hi Layla!</h2>
      <hr>
      <p class="panel">
        Which game would you like to play?<br><br>
        <%= link_to "List One", list_path(:list_one), data: { no_turbolink: true } %> |
        <%= link_to "Hard", hard_words_path(:list_one), data: { no_turbolink: true } %> |
        <%= link_to "Practice", practice_path(:list_one), data: { no_turbolink: true } %><br>
        <%= link_to "List Two", list_path(:list_two), data: { no_turbolink: true } %> |
        <%= link_to "Hard", hard_words_path(:list_two), data: { no_turbolink: true } %> |
        <%= link_to "Practice", practice_path(:list_two), data: { no_turbolink: true } %><br>
        <%= link_to "List Three", list_path(:list_three), data: { no_turbolink: true } %> |
        <%= link_to "Hard", hard_words_path(:list_three), data: { no_turbolink: true } %> |
        <%= link_to "Practice", practice_path(:list_three), data: { no_turbolink: true } %><br>
        <%= link_to "List Four", list_path(:list_four), data: { no_turbolink: true } %> |
        <%= link_to "Hard", hard_words_path(:list_four), data: { no_turbolink: true } %> |
        <%= link_to "Practice", practice_path(:list_four), data: { no_turbolink: true } %><br>
        <%= link_to "Random Words", random_words_path %>
      </p>
    </div>
  </div>
</div>

app/views/points/_points.html.erb
<div class="small-12 medium-6 columns">
  <h1 class="text-center score">
    Today<br>
    <%= todays_points %><br>
    Left<br>
    <%= 10 - todays_points %>
  </h1>
  <h1 class="text-center score">
    Total<br>
    <%= total_points %>
  </h1>
</div>

app/views/points/_success.html.erb
<div class="small-12 columns">
  <h1 class="text-center">Great job Layla! You earned 10 points today!</h1>
  <h1 class="text-center score">
    Total Points<br>
    <%= total_points %>
  </h1>
  <hr>
  <h1 class=text-center>Points left to earn Pig Goes Pop</h1>
  <h1 class="text-center score">
    Total Points<br>
    <%= total_points < 100 ? 100 - total_points : 0 %>
  </h1>
  <div class="text-center"><%= image_tag "pig_goes_pop" %></div>
</div>

app/views/points/_word.html.erb
<div class="small-12 medium-6 columns">
  <h1 class="text-center">
    Hi Layla!<br><br>
    What sight word is this?<br><br>
    <%= word.name %>
  </h1>
  <div class="text-center">
    <%= link_to "Correct", "/points/#{word.id}/correct_answer/" , class: 'button success' %>
    <%= link_to "Incorrect", "/points/#{word.id}/wrong_answer/", class: 'button alert' %>
  </div>
</div>

app/views/points/random_word.html.erb
<div class="row full-width">
  <% if @todays_points == 10 %>
    <%= render 'success', total_points: @total_points %>
  <% else %>
    <%= render 'points', todays_points: @todays_points, total_points: @total_points %>
    <%= render 'word', word: @word %>
  <% end %>
</div>

app/views/words/edit.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1 class="text-center">Add New Tweet</h1>
      <div>
      <%= form_for @word do |f| %>
        <% if @word.errors.any? %>
          <div id="error_explanation">
            <h2>The following prevented your Word from being saved:</h2>
            <ul>
              <% @word.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="row">
          <div class="medium-12 columns">
            <div class="field">
              <%= f.label :name, class: "hide" %>
              <%= f.text_area :name, placeholder: "Add word here", value: "#{@word.name}" %>
            </div>
          </div>
        </div>
        <div class="actions text-center">
          <%= f.submit 'Update', class: 'button radius large' %>
          <%= link_to "Cancel", word_path(@word), id: "cancel", class: 'button radius large alert' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/words/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1 class="text-center">All Words</h1>
    <table id="words_table" class="display">
      <thead>
        <tr>
          <th>Word</th>
          <th>Correct</th>
          <th>Incorrect</th>
          <th>Difficulty</th>
          <th>Edit</th>
        </tr>
      </thead>
      <tbody>
      <% @words.each do |word| %>
        <tr>
          <td><%= link_to word.name, word_path(word) %></td>
          <td><%= word.right %></td>
          <td><%= word.wrong %></td>
          <td><%= word.difficulty.round(2) %></td> 
          <td><%= link_to "edit", edit_word_path(word) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/words/new.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1 class="text-center">Add New Word</h1>
      <div>
      <%= form_for @word do |f| %>
        <% if @word.errors.any? %>
          <div id="error_explanation">
            <h2>The following prevented your Word from being saved:</h2>
            <ul>
              <% @word.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="row">
          <div class="medium-12 columns">
            <div class="field">
              <%= f.label :name, class: "hide" %>
              <%= f.text_area :name, placeholder: "Add word here", value: "#{@word.name}" %>
            </div>
          </div>
        </div>
        <div class="actions text-center">
          <%= f.submit 'Create', class: 'button radius large' %>
          <%= link_to "Cancel", root_path, id: "cancel", class: 'button radius large alert' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/words/show.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1 class="text-center"><%= @word.name %></h1>
    <div class="text-center">
      <%= link_to "Edit", edit_word_path(@word), class: "button large" %>
    </div>
  </div>
</div>